# Generated by Django 5.2 on 2025-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default='No image', upload_to='images/'),
            preserve_default=False,
        ),
    ]
